POST http://localhost:3000/auth/register
Content-Type: application/json

{"username":"jojo1","password":"123456"}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{"username":"jojo1","password":"123456"}

###

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8xIiwiaWF0IjoxNjY4NzA4NDMxLCJleHAiOjE2NjkzMTMyMzF9.GZW9UHEFqDQCn3e7fhi6Pvm1ZJPu7owpjQDuaAkZTG8
