POST http://localhost:3000/auth/register
Content-Type: application/json

{"username":"jojo2","password":"123456"}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{"username":"jojo2","password":"123456"}

###

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8xIiwiaWF0IjoxNjY4NzA4NDMxLCJleHAiOjE2NjkzMTMyMzF9.GZW9UHEFqDQCn3e7fhi6Pvm1ZJPu7owpjQDuaAkZTG8
###

POST http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8xIiwiaWF0IjoxNjY4NzA4NDMxLCJleHAiOjE2NjkzMTMyMzF9.GZW9UHEFqDQCn3e7fhi6Pvm1ZJPu7owpjQDuaAkZTG8
Content-Type: application/json

{"content":"this is content"}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/7b85093f-cdb6-49b1-be0e-e1b26cc795e1


###

PATCH http://localhost:3000/post/7e6d2413-a1a9-45e3-9ce9-665a5d39ef6d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8xIiwiaWF0IjoxNjY4NzA4NDMxLCJleHAiOjE2NjkzMTMyMzF9.GZW9UHEFqDQCn3e7fhi6Pvm1ZJPu7owpjQDuaAkZTG8
Content-Type: application/json

{"content":"worked"}

###

DELETE http://localhost:3000/post/7ea89845-f20a-428a-a9b2-8d2e9eea7eb2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8xIiwiaWF0IjoxNjY4NzA4NDMxLCJleHAiOjE2NjkzMTMyMzF9.GZW9UHEFqDQCn3e7fhi6Pvm1ZJPu7owpjQDuaAkZTG8
Content-Type: application/json

###

POST http://localhost:3000/like/7e6d2413-a1a9-45e3-9ce9-665a5d39ef6d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8yIiwiaWF0IjoxNjY4NzgyNzEzLCJleHAiOjE2NjkzODc1MTN9.jBvMaU1uVt129Lg3CrBc2FxddrYjxUM-3_BITOJ3dTI
Content-Type: application/json

###

DELETE http://localhost:3000/like/7e6d2413-a1a9-45e3-9ce9-665a5d39ef6d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvam8yIiwiaWF0IjoxNjY4NzgyNzEzLCJleHAiOjE2NjkzODc1MTN9.jBvMaU1uVt129Lg3CrBc2FxddrYjxUM-3_BITOJ3dTI
Content-Type: application/json